### ISSUE TITLE
Turn off `no-await-in-loop`

### ISSUE THREAD

**Issue by seb-cr** [comicrelief/eslint-config#22]
Often using `await` in a loop is the easiest and safest way to iterate over a list with some async operations. `async`/`await` has been supported natively in Node for several versions now so I think this rule no longer applies, except maybe in front-end code that has to be transpiled to an older JS/ES version.

**Comment by dipasqualew** [comment]
I second this. However we aim to share `eslint-config` with the frontend as well. We can probably disable it by default and re-enable it in a `frontend.yml` mixin?
