### ISSUE TITLE
Turn off conflicting rules in TypeScript config

### ISSUE THREAD

**Issue by seb-cr** [comicrelief/eslint-config#24]
Some `typescript-eslint` rules conflict with `eslint`'s default set of rules, leading to some contradictory errors:

![20201215 eslint semi](https://user-images.githubusercontent.com/49983670/102471686-68369880-404d-11eb-8352-d506d2a29c2f.png)

In each case the need to turn off the `eslint` rule is documented in the `typescript-eslint` docs ([example](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/semi.md)), however I haven't found a complete list of these rules. `semi` and `no-shadow` are the ones I've run into so far.

**Comment by dipasqualew** [comment]
I assume we are going to enforce semicolons?
